### ISSUE TITLE
GSD language? 

### ISSUE THREAD

**Issue by wallymathieu** [learn-fsharp/fsharp-ecosystem#1]
It would perhaps be good to provide a clearer attribute than GSD? Persons new to this context does not know what is meant by the abbreviation.

**Comment by cloudRoutine** [comment]
getting shit done
this is all really rough, I'm just getting started on all of it

**Comment by wallymathieu** [comment]
Yes, f# is quite nice for getting stuff done. I started looking at this page since I haven't written much in f#. http://assertfail.gewalli.se/2015/08/21/fsharp-2-weeks-later.html
